name: musicblocks
version: '3.1.0'
summary: Visual Programming Language for Exploring Math, Music, and Programming
description: |
 Visual Programming Language for Exploring Math, Music, and Programming

grade: stable
confinement: strict
base: core18
architectures:
- build-on: amd64

parts:
  desktop-gtk3:
    build-packages:
    - build-essential
    - libgtk-3-dev
    make-parameters:
    - FLAVOR=gtk3
    plugin: make
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: gtk
    stage-packages:
    - libxkbcommon0
    - ttf-ubuntu-font-family
    - dmz-cursor-theme
    - light-themes
    - adwaita-icon-theme
    - gnome-themes-standard
    - shared-mime-info
    - libgtk-3-0
    - libgdk-pixbuf2.0-0
    - libglib2.0-bin
    - libgtk-3-bin
    - unity-gtk3-module
    - libappindicator3-1
    - locales-all

  musicblocks:
    plugin: dump
    source: https://github.com/srevinsaju/musicblocks-app/releases/download/continuous/Musicblocks_3.1.0_amd64.deb 
    source-type: deb
    after:
      - desktop-gtk3
    stage-packages:
      - libasound2
      - libgconf2-4
      - libnotify4
      - libnspr4
      - libnss3
      - libpcre3
      - libpulse0
      - libxss1
      - libxtst6
      - libdrm2
      - libgbm1
      - libwayland-server0
      - libx11-xcb1
      - libxcb-dri3-0
      - libgtk2.0-0

apps:
  musicblocks:
    desktop: usr/share/applications/musicblocks.desktop
    command: env TMPDIR=$XDG_RUNTIME_DIR PATH=/usr/local/bin:${PATH} ${SNAP}/bin/desktop-launch $SNAP/opt/Musicblocks/musicblocks --no-sandbox

plugs:
  desktop:
  desktop-legacy:
  x11:
  unity7:
  wayland:
  opengl:
  home:
  gsettings:
  browser-support:
  pulseaudio:
  network:
