

name: Continuous

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]


jobs:
  linux:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Snap Configure
        env:
          SNAP_TOKEN: ${{ secrets.SNAPCRAFT_TOKEN }}
        run: |
          sudo snap install snapcraft --classic
          echo $SNAP_TOKEN | snapcraft login --with -
          
      - run: npm i
      - run: git clone https://github.com/sugarlabs/musicblocks
      - run: sh ./patch.sh
      - run: npx electron-builder --linux appimage --publish never
    
      - name: Patch AppImage
        run: |
          mkdir -p dist/appimage
          cd dist/
          ./*.AppImage --appimage-extract
          cp linux-unpacked/resources/app.asar squashfs-root/resources/.
          wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
          chmod +x appimagetool-x86_64.AppImage
          mv squashfs-root AppDir
          rm Musicblocks*.AppImage
          ./appimagetool-x86_64.AppImage --comp gzip AppDir -n
          ls 
          mv Musicblocks*.AppImage appimage/.
          chmod +x appimage/*.AppImage
          cd ..
    
      - run: npx electron-builder --linux snap --publish never 
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: move snap
        run: |
          mkdir -p dist/snap
          mv dist/*.snap dist/snap/.
      
      - run: npx electron-builder --linux deb --publish never
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: move deb
        run: |
          mkdir -p dist/deb
          mv dist/*.deb dist/deb/.

      - name: Upload Debian
        uses: actions/upload-artifact@v1.0.0
        with:
          name: Musicblocks-continuous-x86_64.deb
          path: 'dist/deb/'

      - name: Upload Appimage
        uses: actions/upload-artifact@v1.0.0
        with:
          name: Musicblocks-continuous-x86_64.AppImage
          path: 'dist/appimage/'
      
      - name: Upload Snap
        uses: actions/upload-artifact@v1.0.0
        with:
          name: Musicblocks-continuous-x86_64.snap
          path: 'dist/snap/'
      

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm i
      - run: git clone https://github.com/sugarlabs/musicblocks


      - run: sh ./patch.sh
      - run: npx electron-builder --win --publish never
        env: 
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          mkdir -p dist/exe
          mv dist/*.exe dist/exe/.
    
      - name: Upload Windows exe
        uses: actions/upload-artifact@v1.0.0
        with:
          name: Musicblocks-continuous-x86_64.exe
          path: 'dist/exe/'

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm i
      - run: brew install gnu-sed
      - run: git clone https://github.com/sugarlabs/musicblocks

      - name: Run gsed
        run: gsed -i 's/sed/gsed/g' patch.sh

      - run: sh ./patch.sh
      - run: npx electron-builder --mac --publish never
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          mkdir -p dist/dmg
          mv dist/*.dmg dist/dmg/.
    
      - name: Upload MacOS DMG
        uses: actions/upload-artifact@v1.0.0
        with:
          name: Musicblocks-continuous-x86_64.dmg
          path: 'dist/dmg/'

  Release:
    needs: [macos, windows, linux]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [3.8]

    steps:
    - uses: actions/download-artifact@v1
      with:
        name: Musicblocks-continuous-x86_64.dmg
    - uses: actions/download-artifact@v1
      with:
        name: Musicblocks-continuous-x86_64.exe
    - uses: actions/download-artifact@v1
      with:
        name: Musicblocks-continuous-x86_64.snap
    - uses: actions/download-artifact@v1
      with:
        name: Musicblocks-continuous-x86_64.AppImage
    - uses: actions/download-artifact@v1
      with:
        name: Musicblocks-continuous-x86_64.deb 
    

    - name: Release
      uses: marvinpinto/action-automatic-releases@latest
      if: github.ref == 'refs/heads/master'
      with:
        automatic_release_tag: continuous
        title: continuous
        files: |
          Musicblocks-continuous-x86_64.dmg
          Musicblocks-continuous-x86_64.exe
          Musicblocks-continuous-x86_64.snap
          Musicblocks-continuous-x86_64.AppImage
          Musicblocks-continuous-x86_64.deb

        repo_token: ${{ secrets.GITHUB_TOKEN }} 
